### ISSUE TITLE
Should MAML integration take place in the API? Or via a job?

### ISSUE THREAD

**Issue by brentstineman** [SimpleCloudManagerProject/SCAMP#21]
Initial implementation is doing this via continuously running job. Just want to create a discussion item related to if this should be in the API or in the job so we can hash pros/cons to the approach...

**Comment by GabrieleCastellani** [comment]
Implementation chosen because create, start and stop the VM takes some time and didn't want to "stress" the IIS thread doing long running operation. 
Then operations like: 
- "verify availability of a name" 
- "verify the status of a VM"
can be tied directly to the WebApi.

If you want to change it is a small change because the biggest part of the code is on the "Provisioning Library" that is the DLL used to pilot Azure Service Manager.

We can discuss it later
