### ISSUE TITLE
misc. Group Management Bugs

### ISSUE THREAD

**Issue by brentstineman** [SimpleCloudManagerProject/SCAMP#217]
When adding a group: 
* Group name was trimmed and turned into lower case (sent “Test Group” and got back “testgroup”)
[10:36:34 AM] Ville Rantala: * Description was not stored (or maybe it was stored, but not returned)
[10:37:21 AM] Ville Rantala: * After I had created a group and then re-requested my groups (using /api/users/993a3226-219b-4a33-acfb-1af61e66fa10/groups/admin), run into an internal server error

When retrieving a group: 
null pointer on line 62 of SCAMP\ScampApi\Controllers\UsersGroupsController.cs (missing volatile store record?)

**Comment by vergenzt** [comment]
> "Group name was trimmed and turned into lower case (sent “Test Group” and got back “testgroup”) "

This looks like it was intentional: [GroupsController.cs#L93](https://github.com/SimpleCloudManagerProject/SCAMP/blob/master/ScampApi/Controllers/GroupsController.cs#L93) Should this be changed?

**Comment by vergenzt** [comment]
1. Group names are trimmed deliberately. (See link in comment above.) We should discuss.
2. Description, budget amounts, and expiration date were not being stored. I have a PR that I'm about ready to submit.
3. Creating and re-requesting groups was running into an exception because the stuff in volatile storage was not being created for new groups until about 20 minutes ago with @brentstineman's #220.
