### ISSUE TITLE
User rights should impact Dashboard, Group Manager views and available actions

### ISSUE THREAD

**Issue by shekr** [SimpleCloudManagerProject/SCAMP#238]
-System Admins should only be able to see the System Settings tab.
-Group Admins should only be able to see the Dashboard and Group Manager tabs.
-Group Managers should only be able to see the Dashboard and Group Manager tabs. Within the Group Manager tab, they should not have access to editing the Group Budget on the Summary view and they should not have access to the "Manager" check box on the Users view.
-Users should only be able to see the Dashboard tab. Within the Dashboard tab they should only be able to see the Student view. This has already been resolved by https://github.com/SimpleCloudManagerProject/SCAMP/commit/342a0bbf03adc719c3afd3ac17b9cd11554702ba

**Comment by vjrantal** [comment]
I had missed this issue and created parts of it as https://github.com/SimpleCloudManagerProject/SCAMP/issues/251. These who could be implemented at the same time, but depend on certain properties coming from https://github.com/SimpleCloudManagerProject/SCAMP/issues/253.

**Comment by vjrantal** [comment]
Here http://www.simplecloudmgr.org/docs/features/resourceusage/ it is stated:

> Group Manager is a member of the group that add/manage other users to the group

@brentstineman: I'd like to check some details about the manage part. Can group managers edit the per-user budget? Also, can group managers delete other users and if yes, can they also delete other group managers?

The description of this issue already mentions that group managers should not be able to touch the checkbox that toggles the `isManager`-flag so that part is clear.

**Comment by brentstineman** [comment]
For the moment, no. Group managers should not be able to alter user budgets. We'll take feedback from adopters and re-evaluate this decision at a later point.

**Comment by vjrantal** [comment]
Implementation merged via https://github.com/SimpleCloudManagerProject/SCAMP/pull/260.
